### ISSUE TITLE
Add a Query route and an Action route to your microservice

### ISSUE THREAD

**Issue by eforgacs** [NYU-DevOps-2022/orders#19]

**Comment by phuang07** [comment]
I already set up a basic query route for "find_by_customer", see: https://github.com/NYU-DevOps-2022/orders/blob/issue_29/service/routes.py#L58

You may follow the same approach to add additional query route.

**Comment by eforgacs** [comment]
Another attribute within the order headers is `date_order`. Would it be useful to have a function, e.g. `find_by_date_order()` that filters by `date_order`?

**Comment by eforgacs** [comment]
We have a pull request open here: https://github.com/NYU-DevOps-2022/orders/pull/33

Take a look and let us know what you think. Thanks!
