### ISSUE TITLE
Implement a User Interface with Automated BDD Testing

### ISSUE THREAD

**Issue by eforgacs** [NYU-DevOps-2022/orders#22]

**Comment by eforgacs** [comment]
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Orders-620fd087d51bbb0012a59ff5/issues/NYU-DevOps-2022/orders/22?planning-poker) with ZenHub @mc7836 @phuang07 @ShreyRupani @Sijia-Hao1998

**Comment by phuang07** [comment]
![image](https://user-images.githubusercontent.com/353542/162066193-ee5f7ae7-5718-4971-971c-653c550e4061.png)

![image](https://user-images.githubusercontent.com/353542/162066104-90e481fb-0bb8-490f-be09-72efcf241390.png)
