### ISSUE TITLE
Spin up a local dev env

### ISSUE THREAD

**Issue by phuang07** [NYU-DevOps-2022/orders#6]
**As a**  developer
 **I need** a development environment 
 **So that** I can develop new feature for "orders"
   
 ### Details and Assumptions
 * Using python >= v3.6
 * Using docker container within Vscode
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given I clone the project to my local machine
 When I call `code .` in my local project directory
 Then I should see my project open in vscode and docker remote container is running
 ```

**Comment by ShreyRupani** [comment]
team will create the .devcontainer folder and make sure that the Dockerfile, docker-compose.yml file, and devcontainers.json file is configured correctly so that all team members will get the proper remote container environment when they clone the repo.

**Comment by phuang07** [comment]
Start the flask project by running `flask run` inside the container

Then visit: http://localhost:8000
